name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '3 7,14,21 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Clone Source
        uses: actions/checkout@v4

      - name: Make Directories
        run: mkdir -p build

      - name: Install Dependencies
        shell: bash
        run: scripts/requirements.sh

      - name: Build Resources
        shell: bash
        run: scripts/build.sh ${GITHUB_SHA}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            keep_files: true  # Some plugins do not always rebuild!!
            allow_empty_commit: true  # Add a commit anyway to show we tried
            #cname: inkyframe.pimoroni.com